In [1]:
# Import numpy
import numpy as np

In [2]:
'''
The basic type on numpy is the ndarray, it can have several dimensions, the main atributs of ndarray are:
- ndarray.dim: number of dimensions of the arrar (number of axes)
- ndarray.shape: returns a tuple of integers corresponding to the size of every dimension
- ndarray.dtype: types of all elements of the array
- ndarray.data: the data of the array
- ndarray.size: returns the total number of elements
'''

'\nThe basic type on numpy is the ndarray, it can have several dimensions, the main atributs of ndarray are:\n- ndarray.dim: number of dimensions of the arrar (number of axes)\n- ndarray.shape: returns a tuple of integers corresponding to the size of every dimension\n- ndarray.dtype: types of all elements of the array\n- ndarray.data: the data of the array\n'

In [3]:
# ndarray creation:
ti = np.array([1, 2, 3, 4])
ti

array([1, 2, 3, 4])

In [4]:
ti.dtype

dtype('int64')

In [7]:
ti1 = np.array([1.5, 2.5, 3.5, 4.6 ])
ti1.dtype

dtype('float64')

In [8]:
ti2d = np.array([[1.5, 2, 3], [4, 5, 6]])
ti2d

array([[1.5, 2. , 3. ],
       [4. , 5. , 6. ]])

In [10]:
# We can indicate the type of the array implicitly:
ti2d2 = np.array([[1, 2, 3], [4, 5, 6]], dtype=float)
ti2d2

array([[1., 2., 3.],
       [4., 5., 6.]])

In [11]:
# We can indicate the type of the array implicitly:
ti2d3 = np.array([[1, 2, 3], [4, 5, 6]], dtype=int)
ti2d3

array([[1, 2, 3],
       [4, 5, 6]])

In [12]:
# show the shape:
ti2d3.shape

(2, 3)

In [13]:
# show the dimension (number of axes)
ti2d3.ndim

2

In [14]:
# Array of zeros:
tz2d = np.zeros((3,4))
tz2d

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [15]:
# Array of ones:
to2d = np.ones((3,4))
to2d

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [16]:
# Create an identity matrix
id2d = np.eye(5)
id2d

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [17]:
# Create an array with uninitialized values
tni2d = np.empty((3,4))
tni2d

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [19]:
# Array spaced by 5 between 0 and 40
ts1d = np.arange(0, 40, 5)
ts1d

array([ 0,  5, 10, 15, 20, 25, 30, 35])

In [20]:
# Array with 8 elements equally spaced between 0 and 35
ts1d2 = np.linspace(0, 35, 8)
ts1d2

array([ 0.,  5., 10., 15., 20., 25., 30., 35.])

In [22]:
# Array with random values
ta2d = np.random.rand(3,5)
ta2d

array([[0.17742606, 0.04953466, 0.93621062, 0.26060949, 0.79498727],
       [0.94769399, 0.42568367, 0.88018702, 0.30181989, 0.35960423],
       [0.5829056 , 0.53585396, 0.43488529, 0.3798742 , 0.13316199]])

In [30]:
# Generate array with random elements following a normal (gaussian) law:  ---------------------------Verify
s = np.random.normal(0, 1, size = (3,5))
s

array([[-0.01316411, -1.23781697,  0.10185804,  0.20272313,  1.24384914],
       [ 1.94951212, -0.33966502, -0.69928092,  0.26918844,  0.6332876 ],
       [-0.84772949,  0.03975939, -0.14395835, -1.76677511, -0.70148001]])

In [31]:
tr = np.arange(20)
tr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])

In [32]:
tr.reshape(4,5)

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19]])

In [33]:
tr.reshape(2,10)

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19]])

In [34]:
tr.reshape(20)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])

In [37]:
# Array with first 6 elements:
tr[:6]

array([0, 1, 2, 3, 4, 5])

In [38]:
# Pick values with a specific step (in this case 2) until the 6th element
tr[:6:2]

array([0, 2, 4])

In [40]:
# the variable a points to first 2 elements of tr:
a = tr[:2]
a

array([0, 1])

In [42]:
# if we modify the first elements of a then the first element of tr will be modified
a[0] = 3
tr

array([ 3,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])

In [43]:
# To obtain a copy of a array we need to use the method copy:
b = tr[:2].copy()
b

array([3, 1])

In [44]:
b[0] = 4
b

array([4, 1])

In [45]:
tr

array([ 3,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])

In [46]:
# Example: to extraire parts of a multidimensional array:
ta2d = np.random.rand(3,5)
ta2d

array([[0.95384077, 0.05698636, 0.19936221, 0.02477151, 0.87363037],
       [0.30563857, 0.32681679, 0.57398898, 0.43356228, 0.28372338],
       [0.9659509 , 0.83508524, 0.75940941, 0.66562719, 0.13591699]])

In [47]:
ta2d[:2,:2]

array([[0.95384077, 0.05698636],
       [0.30563857, 0.32681679]])

In [51]:
# Extraction of odd colons of ta2d:
ta2d[:, 1::2]

array([[0.05698636, 0.02477151],
       [0.32681679, 0.43356228],
       [0.83508524, 0.66562719]])

In [52]:
# When we do an iteration on a multidimensional array the last dimension index change the fastest 
# and the lower dimension index changes the slowest
for x in ta2d:
    print(x)

[0.95384077 0.05698636 0.19936221 0.02477151 0.87363037]
[0.30563857 0.32681679 0.57398898 0.43356228 0.28372338]
[0.9659509  0.83508524 0.75940941 0.66562719 0.13591699]
